spring:
    application:
        name: melog
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    profiles:
        active: dev
    config:
        import: classpath:clova-properties.yml
server:
    port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html