spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/melog
    username: melog
    password: melog
    driver-class-name: org.postgresql.Driver
    

  jpa:
    hibernate:
      ddl-auto: update   # 또는 create, validate, none

    show-sql: true        # 콘솔에 SQL 출력
    # properties:
    #   hibernate:
        # format_sql: true  # SQL 예쁘게 출력

  # 필요 시 flyway나 liquibase도 여기에 추가 가능