spring:
  jpa:
    properties:
      hibernate:
        ddl-auto: validate
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: melog
    show-sql: false

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}?currentSchema=melog
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: melog
    default-schema: melog

  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
      enabled: true

logging:
  level:
    com.melog.melog: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when-authorized

server:
  port: ${SERVER_PORT:443}
  ssl:
    bundle: app-cert

spring:
  ssl:
    bundle:
      pem:
        app-cert:
          certificate: /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem
          private-key: /etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem
  error:
    include-stacktrace: never
    include-message: always
