spring:
  datasource:
    url: jdbc:postgresql://postgres/melog
    username: melog
    password: melog
    driver-class-name: org.postgresql.Driver
    

  jpa:
    hibernate:
      ddl-auto: create-drop   # 기존 테이블을 삭제하고 새로 생성

    show-sql: true        # 콘솔에 SQL 출력
    properties:
      hibernate:
        format_sql: true  # SQL 예쁘게 출력