spring:
    profiles:
        active: prod
    
    # 프로덕션 JPA 설정 (안전한 validate 사용)
    jpa:
        hibernate:
            ddl-auto: validate  # 운영에서는 validate 사용
        show-sql: false
        properties:
            hibernate:
                format_sql: false
                dialect: org.hibernate.dialect.PostgreSQLDialect
    
    # 프로덕션 데이터베이스 설정
    datasource:
        url: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
        username: ${POSTGRES_USER}
        password: ${POSTGRES_PASSWORD}
        driver-class-name: org.postgresql.Driver
        hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            connection-timeout: 30000
            idle-timeout: 600000
            max-lifetime: 1800000

    # Production에서도 파일 업로드 설정 필요
    servlet:
      multipart:
        max-file-size: 3MB
        max-request-size: 3MB
        enabled: true

  # Production 로깅 설정
logging:
  level:
    com.melog.melog: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator 설정 (헬스체크용)
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: when-authorized

# Clova 설정은 환경변수로 관리 (docker-compose.prod.yml에서 설정)

# 서버 설정
server:
  port: 8080
  error:
    include-stacktrace: never
    include-message: always 
