spring:
    application:
        name: melog
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    profiles:
        active: dev

    servlet:
        multipart:
            max-file-size: 3MB
            max-request-size: 3MB
            enabled: true
server:
    port: 8080

# springdoc:
#   api-docs:
#     path: /api-docs
#   swagger-ui:
#     path: /swagger-ui.html