spring:
    application:
        name: melog
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: true
    profiles:
        active: dev
server:
    port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html