--
-- PostgreSQL database dump
--

-- Dumped from database version 15.4 (Debian 15.4-2.pgdg120+1)
-- Dumped by pg_dump version 15.4 (Debian 15.4-2.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: emotion_type; Type: TYPE; Schema: melog; Owner: melog
--

CREATE TYPE melog.emotion_type AS ENUM (
    'JOY',
    'EXCITEMENT',
    'CALMNESS',
    'ANGER',
    'SADNESS',
    'GUIDANCE'
);


ALTER TYPE melog.emotion_type OWNER TO melog;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: emotion_keyword; Type: TABLE; Schema: melog; Owner: melog
--

CREATE TABLE melog.emotion_keyword (
    weight integer NOT NULL,
    id bigint NOT NULL,
    record_id bigint NOT NULL,
    keyword character varying(255) NOT NULL
);

ALTER TABLE melog.emotion_keyword OWNER TO melog;

--
-- Name: emotion_keyword_id_seq; Type: SEQUENCE; Schema: melog; Owner: melog
--

ALTER TABLE melog.emotion_keyword ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME melog.emotion_keyword_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emotion_record; Type: TABLE; Schema: melog; Owner: melog
--

CREATE TABLE melog.emotion_record (
    date date NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    summary text,
    text text
);


ALTER TABLE melog.emotion_record OWNER TO melog;

--
-- Name: emotion_record_id_seq; Type: SEQUENCE; Schema: melog; Owner: melog
--

ALTER TABLE melog.emotion_record ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME melog.emotion_record_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emotion_score; Type: TABLE; Schema: melog; Owner: melog
--

CREATE TABLE melog.emotion_score (
    percentage integer NOT NULL,
    step integer NOT NULL,
    id bigint NOT NULL,
    record_id bigint NOT NULL,
    emotion_type character varying(255) NOT NULL,
    CONSTRAINT emotion_score_emotion_type_check CHECK (((emotion_type)::text = ANY ((ARRAY['JOY'::character varying, 'EXCITEMENT'::character varying, 'CALMNESS'::character varying, 'ANGER'::character varying, 'SADNESS'::character varying, 'GUIDANCE'::character varying])::text[])))
);


ALTER TABLE melog.emotion_score OWNER TO melog;

--
-- Name: emotion_score_id_seq; Type: SEQUENCE; Schema: melog; Owner: melog
--

ALTER TABLE melog.emotion_score ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME melog.emotion_score_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: sample; Type: TABLE; Schema: melog; Owner: melog
--

CREATE TABLE melog.sample (
    id bigint NOT NULL,
    content character varying(255),
    title character varying(255)
);


ALTER TABLE melog.sample OWNER TO melog;

--
-- Name: sample_id_seq; Type: SEQUENCE; Schema: melog; Owner: melog
--

ALTER TABLE melog.sample ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME melog.sample_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_selected_emotion; Type: TABLE; Schema: melog; Owner: melog
--

CREATE TABLE melog.user_selected_emotion (
    percentage integer NOT NULL,
    step integer NOT NULL,
    id bigint NOT NULL,
    record_id bigint NOT NULL,
    emotion_type character varying(255) NOT NULL,
    CONSTRAINT user_selected_emotion_emotion_type_check CHECK (((emotion_type)::text = ANY ((ARRAY['JOY'::character varying, 'EXCITEMENT'::character varying, 'CALMNESS'::character varying, 'ANGER'::character varying, 'SADNESS'::character varying, 'GUIDANCE'::character varying])::text[])))
);


ALTER TABLE melog.user_selected_emotion OWNER TO melog;

--
-- Name: user_selected_emotion_id_seq; Type: SEQUENCE; Schema: melog; Owner: melog
--

ALTER TABLE melog.user_selected_emotion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME melog.user_selected_emotion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: melog; Owner: melog
--

CREATE TABLE melog.users (
    created_at timestamp(6) without time zone NOT NULL,
    id bigint NOT NULL,
    nickname character varying(255) NOT NULL
);


ALTER TABLE melog.users OWNER TO melog;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: melog; Owner: melog
--

ALTER TABLE melog.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME melog.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: emotion_keyword emotion_keyword_pkey; Type: CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.emotion_keyword
    ADD CONSTRAINT emotion_keyword_pkey PRIMARY KEY (id);


--
-- Name: emotion_record emotion_record_pkey; Type: CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.emotion_record
    ADD CONSTRAINT emotion_record_pkey PRIMARY KEY (id);


--
-- Name: emotion_score emotion_score_pkey; Type: CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.emotion_score
    ADD CONSTRAINT emotion_score_pkey PRIMARY KEY (id);


-- Name: sample sample_pkey; Type: CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.sample
    ADD CONSTRAINT sample_pkey PRIMARY KEY (id);


--
-- Name: user_selected_emotion user_selected_emotion_pkey; Type: CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.user_selected_emotion
    ADD CONSTRAINT user_selected_emotion_pkey PRIMARY KEY (id);


--
-- Name: user_selected_emotion user_selected_emotion_record_id_key; Type: CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.user_selected_emotion
    ADD CONSTRAINT user_selected_emotion_record_id_key UNIQUE (record_id);


--
-- Name: users users_nickname_key; Type: CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.users
    ADD CONSTRAINT users_nickname_key UNIQUE (nickname);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: emotion_keyword fk6x9ocopjj9gk6eaopwrv0pvkd; Type: FK CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.emotion_keyword
    ADD CONSTRAINT fk6x9ocopjj9gk6eaopwrv0pvkd FOREIGN KEY (record_id) REFERENCES melog.emotion_record(id);


--
-- Name: emotion_score fk7ee5e05pn5fh7j8anecw3k5bc; Type: FK CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.emotion_score
    ADD CONSTRAINT fk7ee5e05pn5fh7j8anecw3k5bc FOREIGN KEY (record_id) REFERENCES melog.emotion_record(id);


--
-- Name: emotion_record fkcn3evf7yqc9fipn13o6xvnl90; Type: FK CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.emotion_record
    ADD CONSTRAINT fkcn3evf7yqc9fipn13o6xvnl90 FOREIGN KEY (user_id) REFERENCES melog.users(id);


--
-- Name: user_selected_emotion fkt5qratukiv8apf96k0a5i8c53; Type: FK CONSTRAINT; Schema: melog; Owner: melog
--

ALTER TABLE ONLY melog.user_selected_emotion
    ADD CONSTRAINT fkt5qratukiv8apf96k0a5i8c53 FOREIGN KEY (record_id) REFERENCES melog.emotion_record(id);


--
-- PostgreSQL database dump complete
--

