-- V2: 음성 파일 및 감정 코멘트 기능 추가
-- 기존 테이블에 새로운 필드들 추가

-- 1. emotion_record 테이블에 음성 파일 관련 필드 추가
ALTER TABLE melog.emotion_record 
ADD COLUMN audio_file_path VARCHAR(500),
ADD COLUMN audio_file_name VARCHAR(255),
ADD COLUMN audio_duration INTEGER,
ADD COLUMN audio_file_size BIGINT,
ADD COLUMN audio_mime_type VARCHAR(100);

-- 2. emotion_comments 테이블 생성
CREATE TABLE melog.emotion_comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emotion_type VARCHAR(50) NOT NULL,
    step INTEGER NOT NULL,
    comment TEXT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT true,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    
    -- 감정 타입과 단계의 조합은 유니크해야 함
    CONSTRAINT uk_emotion_type_step UNIQUE (emotion_type, step),
    
    -- emotion_type은 기존 enum 타입과 일치해야 함
    CONSTRAINT chk_emotion_type CHECK (
        emotion_type IN ('JOY', 'EXCITEMENT', 'CALMNESS', 'ANGER', 'SADNESS', 'GUIDANCE')
    ),
    
    -- step은 1-5 범위
    CONSTRAINT chk_step_range CHECK (step >= 1 AND step <= 5)
);

-- 3. emotion_record에 emotion_comment_id 외래키 추가
ALTER TABLE melog.emotion_record 
ADD COLUMN emotion_comment_id BIGINT;

-- 4. emotion_score에 emotion_comment_id 외래키 추가
ALTER TABLE melog.emotion_score 
ADD COLUMN emotion_comment_id BIGINT;

-- 5. 외래키 제약조건 추가
ALTER TABLE melog.emotion_record 
ADD CONSTRAINT fk_emotion_record_comment 
FOREIGN KEY (emotion_comment_id) REFERENCES melog.emotion_comments(id);

ALTER TABLE melog.emotion_score 
ADD CONSTRAINT fk_emotion_score_comment 
FOREIGN KEY (emotion_comment_id) REFERENCES melog.emotion_comments(id);

-- 6. 인덱스 생성 (성능 향상)
CREATE INDEX idx_emotion_record_audio_file ON melog.emotion_record(audio_file_path);
CREATE INDEX idx_emotion_record_user_date ON melog.emotion_record(user_id, date);
CREATE INDEX idx_emotion_comments_type_step ON melog.emotion_comments(emotion_type, step);
CREATE INDEX idx_emotion_score_comment ON melog.emotion_score(emotion_comment_id);

-- 7. 기존 데이터에 대한 기본 코멘트 설정
-- (실제 코멘트는 data.sql에서 별도로 삽입)

-- 8. 테이블 소유권 설정
ALTER TABLE melog.emotion_comments OWNER TO melog;
